### ISSUE TITLE
SA-MP not recognizing the Shoebill.dll plugin

### ISSUE THREAD

**Issue by vakho10** [Shoebill/ShoebillPlugin#11]
Hi, I know the SA-MP is kind of dead but I would like to run Java code instead of Pawn so I would like your help here.
The FTP url for Shoebill server files is down so I don't event know how the project should be assembled anymore. 
I'm firstly trying to at least run the Shoebillplugin. I've managed to build it (tagged with 1.3 version) on 32bit windows10 with 32bit Java 1.8. 
However, when I put the `Shoebill.dll` inside the server's plugins folder and run the server - I get the following:
```
Server Plugins
--------------
 Loading plugin: Shoebill
  Failed.
 Loaded 0 plugins.
```
If you have the server files or if you know where to put what, could you direct me? @123marvin123 
Also, what does the startup.bat do which I saw in videos (because there are no files anymore, I try to re-create them)?

**Comment by 123marvin123** [comment]
Hi @vakho10,

thanks for your interest in the project. As you already recognized, the Shoebill project is dead and I guess SA:MP too. I don't know exactly why loading the plugin fails, but the startup.bat just added some java files into the PATH variable, I think it was the path to the "jvm.dll" file in your java runtime environment. You can use the "crash detector" plugin to get a more detailed error message (https://github.com/Zeex/samp-plugin-crashdetect/releases), but make sure you add the plugin in the configuration file before loading Shoebill, otherwise you might not get a result (check the order).

**Comment by vakho10** [comment]
@123marvin123 Thanks :) 
By the way, is there any way of finding the whole "build" project somewhere? I've downloaded it when it was available but I think I've deleted it and the links are down :(

**Comment by 123marvin123** [comment]
I found a project which uses Shoebill and has all the original files in it: https://github.com/Justas-S/ltrp

It also includes the startup.bat file.

**Comment by vakho10** [comment]
@123marvin123 You are a life saver my friend :) Thanks. Now I can run it :)

**Comment by 123marvin123** [comment]
Nice to hear :) I'm going to close this issue then.
